name: Jest Tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
        env:
          CI: true
          DATABASE_URL: postgres://zfixxikjvlrinp:03e432445c9f927e31ec217e549b13de693c3d8dc685904a329484c6392ce608@ec2-34-233-115-14.compute-1.amazonaws.com:5432/d79d96h9m2mn8b
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}
